# Offense count: 2
Metrics/AbcSize:
  Max: 72

# Offense count: 1
Metrics/CyclomaticComplexity:
  Max: 16

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 43

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 102

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 16

# Offense count: 3
# Cop supports --auto-correct.
Style/AlignArray:
  Enabled: false

# Offense count: 14
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: false

# Offense count: 30
Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

# Offense count: 1
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false
